package com.ihome.controller;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.ihome.common.ApiResponse;
import com.ihome.entity.QuestionnaireAnswer;
import com.ihome.entity.RoommateTag;
import com.ihome.mapper.QuestionnaireAnswerMapper;
import com.ihome.mapper.RoommateTagMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.constraints.NotBlank;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@RestController
@RequestMapping("/questionnaire")
@Tag(name = "问卷管理", description = "室友匹配问卷相关接口")
public class QuestionnaireController {
    private final QuestionnaireAnswerMapper questionnaireMapper;
    private final RoommateTagMapper tagMapper;

    public QuestionnaireController(QuestionnaireAnswerMapper questionnaireMapper, RoommateTagMapper tagMapper) {
        this.questionnaireMapper = questionnaireMapper;
        this.tagMapper = tagMapper;
    }

    @PostMapping("/submit")
    @Operation(summary = "提交问卷", description = "学生提交室友匹配问卷，自动生成标签")
    @SuppressWarnings("unchecked")
    public ApiResponse<Map<String, Object>> submitQuestionnaire(@RequestBody SubmitQuestionnaireRequest req) {
        try {
            // 获取当前登录学生ID
            String studentId = SecurityContextHolder.getContext().getAuthentication().getName();
            
            // 处理answers字段，支持Map和List两种格式
            Map<String, Object> answerMap;
            if (req.getAnswers() instanceof Map) {
                answerMap = (Map<String, Object>) req.getAnswers();
            } else if (req.getAnswers() instanceof List) {
                List<Map<String, Object>> answerList = (List<Map<String, Object>>) req.getAnswers();
                if (!answerList.isEmpty()) {
                    answerMap = answerList.get(0);
                } else {
                    throw new RuntimeException("问卷答案不能为空");
                }
            } else {
                throw new RuntimeException("问卷答案格式错误");
            }
            
            // 验证必填字段 - 检查answerMap中的值
            String sleepTimePreference = (String) answerMap.get("sleepTimePreference");
            String cleanlinessLevel = (String) answerMap.get("cleanlinessLevel");
            String noiseTolerance = (String) answerMap.get("noiseTolerance");
            String eatingInRoom = (String) answerMap.get("eatingInRoom");
            String collectiveSpendingHabit = (String) answerMap.get("collectiveSpendingHabit");
            
            // 验证是否有空值
            boolean hasEmptyField = (sleepTimePreference == null || sleepTimePreference.trim().isEmpty()) ||
                                  (cleanlinessLevel == null || cleanlinessLevel.trim().isEmpty()) ||
                                  (noiseTolerance == null || noiseTolerance.trim().isEmpty()) ||
                                  (eatingInRoom == null || eatingInRoom.trim().isEmpty()) ||
                                  (collectiveSpendingHabit == null || collectiveSpendingHabit.trim().isEmpty());
            
            if (hasEmptyField) {
                // 只返回一次错误信息，避免重复提示
                Map<String, Object> response = new HashMap<>();
                response.put("success", false);
                response.put("message", "请完整填写问卷中的所有选项");
                return ApiResponse.ok(response);
            }
            
            // 删除现有答案
            questionnaireMapper.delete(
                    Wrappers.<QuestionnaireAnswer>lambdaQuery()
                            .eq(QuestionnaireAnswer::getStudentId, studentId)
            );

            // 插入新答案
            QuestionnaireAnswer merged = new QuestionnaireAnswer();
            merged.setStudentId(studentId);
            merged.setSleepTimePreference(sleepTimePreference);
            merged.setCleanlinessLevel(cleanlinessLevel);
            merged.setNoiseTolerance(noiseTolerance);
            merged.setEatingInRoom(eatingInRoom);
            merged.setCollectiveSpendingHabit(collectiveSpendingHabit);
            questionnaireMapper.insert(merged);

            // 自动生成标签
            List<String> autoGeneratedTags = generateTagsFromQuestionnaire(answerMap);
            
            // 检查标签冲突
            List<String> conflicts = checkTagConflicts(autoGeneratedTags, req.getTags());
            if (!conflicts.isEmpty()) {
                Map<String, Object> response = new HashMap<>();
                response.put("success", false);
                response.put("message", "标签冲突，请修改手动选择的标签");
                response.put("conflicts", conflicts);
                response.put("autoGeneratedTags", autoGeneratedTags);
                return ApiResponse.error("标签冲突");
            }

            // 删除现有标签
            tagMapper.delete(
                    Wrappers.<RoommateTag>lambdaQuery()
                            .eq(RoommateTag::getStudentId, studentId)
            );

            // 添加问卷自动生成的标签
            for (String tagName : autoGeneratedTags) {
                RoommateTag tag = new RoommateTag();
                tag.setStudentId(studentId);
                tag.setTagName(tagName);
                tag.setTagType("QUESTIONNAIRE_AUTO");
                tag.setSource("QUESTIONNAIRE");
                tagMapper.insert(tag);
            }

            // 添加手动选择的标签
            if (req.getTags() != null && !req.getTags().isEmpty()) {
                for (String tagName : req.getTags()) {
                    RoommateTag tag = new RoommateTag();
                    tag.setStudentId(studentId);
                    tag.setTagName(tagName);
                    tag.setTagType("MANUAL_POSITIVE");
                    tag.setSource("MANUAL");
                    tagMapper.insert(tag);
                }
            }

            Map<String, Object> response = new HashMap<>();
            response.put("success", true);
            response.put("message", "问卷提交成功");
            response.put("autoGeneratedTags", autoGeneratedTags);
            response.put("conflicts", conflicts);
            
            return ApiResponse.ok(response);
        } catch (Exception e) {
            return ApiResponse.error("问卷提交失败: " + e.getMessage());
        }
    }
    
    /**
     * 根据问卷答案自动生成标签
     */
    private List<String> generateTagsFromQuestionnaire(Map<String, Object> answerMap) {
        List<String> tags = new ArrayList<>();
        
        // 睡眠时间偏好
        String sleepTimePreference = (String) answerMap.get("sleepTimePreference");
        if ("早睡早起".equals(sleepTimePreference)) {
            tags.add("早睡");
        } else if ("晚睡晚起".equals(sleepTimePreference)) {
            tags.add("晚睡");
        } else if ("不固定".equals(sleepTimePreference)) {
            tags.add("作息不规律");
        }
        
        // 整洁程度
        String cleanlinessLevel = (String) answerMap.get("cleanlinessLevel");
        if ("爱整洁".equals(cleanlinessLevel)) {
            tags.add("整洁");
        } else if ("随意".equals(cleanlinessLevel)) {
            tags.add("随意");
        }
        
        // 噪音容忍度
        String noiseTolerance = (String) answerMap.get("noiseTolerance");
        if ("安静".equals(noiseTolerance)) {
            tags.add("安静");
        } else if ("能接受一点噪音".equals(noiseTolerance)) {
            tags.add("适度噪音");
        }
        
        // 房间用餐习惯
        String eatingInRoom = (String) answerMap.get("eatingInRoom");
        if ("经常".equals(eatingInRoom)) {
            tags.add("宿舍用餐");
        } else if ("从不".equals(eatingInRoom)) {
            tags.add("不在宿舍用餐");
        }
        
        // 集体消费意愿
        String collectiveSpendingHabit = (String) answerMap.get("collectiveSpendingHabit");
        if ("愿意".equals(collectiveSpendingHabit)) {
            tags.add("集体消费");
        } else if ("不愿意".equals(collectiveSpendingHabit)) {
            tags.add("独立消费");
        }
        
        return tags;
    }
    
    /**
     * 检查标签冲突
     */
    private List<String> checkTagConflicts(List<String> autoGeneratedTags, List<String> manualTags) {
        List<String> conflicts = new ArrayList<>();
        
        if (manualTags == null || manualTags.isEmpty()) {
            return conflicts;
        }
        
        Map<String, String> conflictMap = Map.of(
            "安静", "吵闹",
            "整洁", "邋遢", 
            "早睡", "晚睡",
            "晚睡", "早睡",
            "宿舍用餐", "不在宿舍用餐",
            "集体消费", "独立消费"
        );
        
        for (String autoTag : autoGeneratedTags) {
            String conflictTag = conflictMap.get(autoTag);
            if (conflictTag != null && manualTags.contains(conflictTag)) {
                conflicts.add(autoTag + " 与 " + conflictTag + " 冲突");
            }
        }
        
        return conflicts;
    }

    @GetMapping("/student/{studentId}")
    @Operation(summary = "获取学生问卷", description = "获取学生的问卷答案和标签信息")
    public ApiResponse<QuestionnaireData> getStudentQuestionnaire(@PathVariable String studentId) {
        List<QuestionnaireAnswer> answers = questionnaireMapper.selectList(
                Wrappers.<QuestionnaireAnswer>lambdaQuery()
                        .eq(QuestionnaireAnswer::getStudentId, studentId)
        );
        
        List<RoommateTag> tags = tagMapper.selectList(
                Wrappers.<RoommateTag>lambdaQuery()
                        .eq(RoommateTag::getStudentId, studentId)
        );

        QuestionnaireData data = new QuestionnaireData();
        data.setAnswers(answers);
        data.setTags(tags.stream().map(RoommateTag::getTagName).toList());
        
        return ApiResponse.ok(data);
    }

    public static class SubmitQuestionnaireRequest {
        @NotBlank
        private String studentId;
        private Object answers;  // 使用Object类型支持Map或List格式
        private List<String> tags;

        // Getters and Setters
        public String getStudentId() { return studentId; }
        public void setStudentId(String studentId) { this.studentId = studentId; }
        public Object getAnswers() { return answers; }
        public void setAnswers(Object answers) { this.answers = answers; }
        public List<String> getTags() { return tags; }
        public void setTags(List<String> tags) { this.tags = tags; }
    }

    public static class QuestionnaireData {
        private List<QuestionnaireAnswer> answers;
        private List<String> tags;

        // Getters and Setters
        public List<QuestionnaireAnswer> getAnswers() { return answers; }
        public void setAnswers(List<QuestionnaireAnswer> answers) { this.answers = answers; }
        public List<String> getTags() { return tags; }
        public void setTags(List<String> tags) { this.tags = tags; }
    }
}